Expose SecurityContext in FlinkClusterSpec
GoogleCloudPlatform/flink-on-k8s-operator pull request #324
Opened 2020-09-17 13:47 UTC by thebalu

Expose the PodSecurityContext for JobManager, TaskManager, and Job pods in the FlinkClusterSpec.
This lets us run them as the Flink user, as mentioned in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/312

2020-09-17 13:49 UTC, thebalu commented
Hi! This is my first time contributing to this project, so please let me know if there are any additional requirements.

I am not sure for example, if this requires an API version change; if so, could you please provide some guidance on how to do it?

2020-09-17 13:51 UTC, thebalu commented
@googlebot I signed it!

2020-09-17 16:47 UTC, functicons requested changes
Thanks for the PR! 

1. Could you update the [CRD doc](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/crd.md) with the new fields? 

2. Update the unit test to cover cases with and without the new fields.

3. I'd prefer keeping the sample YAMLs simple. This feature is not so frequently requested, so I don't want to confuse people with them in the sample YAMLs. For users needing it, they can go to the CRD doc.

2020-09-21 08:47 UTC, thebalu commented
@functicons I've made the requested changes, please review when you have time.

2020-09-23 00:20 UTC, functicons requested changes
A few minor comments.

Could you also add a section in the [user guide](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/docs/user_guide.md#how-to) on the use case and how to set these fields?

2020-09-23 00:20 UTC, functicons commented on docs/crd.md
> +        |__ securityContext
Could you add explanation for these fields below?

2020-09-23 12:01 UTC, thebalu commented
@functicons updated docs

2020-09-23 21:46 UTC, functicons commented
/gcbrun

2020-09-23 21:47 UTC, functicons approved these changes
Thanks!

2020-09-24 00:32 UTC, merged